### ISSUE TITLE
Help me !!  I try to apply a new .pb file but it does not work..

### ISSUE THREAD

**Issue by mking1011** [Syn-McJ/TFClassify-Unity#12]
I want to recognize my fist and palm. 
So I found a new pb file and a label.

I changed the extension of the model from .pb to .bytes, put the model and label in the resource
I set the model file and the label file to the main camera object label of the model and the selected scene.

But it does not work.
I would be so grateful if you could help me.

Attach my pb file and label file
[AttachFile.zip](https://github.com/Syn-McJ/TFClassify-Unity/files/2273349/AttachFile.zip)

**Comment by Syn-McJ** [comment]
Hi @mking1011, I see you have YOLO model. I don't think it will work. Detection example is a port of [Android example from TensorFlow repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android), and they use SSD-Mobilenet models trained using [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection/).

I suggest you to retrain your model with TensorFlow Object Detection API and try again.

**Comment by mking1011** [comment]
Thank you so much for your reply.

I saw the answer and continued studying TensorFlow Object Detection API

And I found the raccoon dataset.
(https://github.com/datitran/raccoon_dataset

https://towardsdatascience.com/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9)

But the pb file did not work.

Did I ever do something wrong?

[output_inference_graph.zip](https://github.com/Syn-McJ/TFClassify-Unity/files/2323098/output_inference_graph.zip)

**Comment by Syn-McJ** [comment]
Hi @mking1011 ,

I can only see the model in your archive attachment, can you please attach the labels too?

**Comment by mking1011** [comment]
Hi @Syn-McJ 
Thanks for the reply

I simply added a raccoon to your coco_labels_list.txt file.
Here is the coco_labels_list I changed
[coco_labels_list.txt](https://github.com/Syn-McJ/TFClassify-Unity/files/2326591/coco_labels_list.txt)

Also, I would appreciate if you looked at the .pbtxt file of the raccoon dataset.
[object-detection_pbtxt.zip](https://github.com/Syn-McJ/TFClassify-Unity/files/2326598/object-detection_pbtxt.zip)


I'm always thankful

**Comment by Syn-McJ** [comment]
@mking1011 I don't think adding racoon label to coco_labels_list.txt will work, object detection is depending on correct amount of labels and the format of the labels file, which is different for ssd-mobilenet.

your object-detection.pbtxt file seems to be in the right format, if you rename its extension to .txt and use it as labels file it should work for your model.

I'll try to find time to check it later today.

**Comment by mking1011** [comment]
@Syn-McJ 

I am just thankful

I also continued the test.
I changed the first item in the coco_labels_list, person, to a raccoon.
I've seen smartphones recognize raccoon since then, but I do not know why.

Thank you for your time.

**Comment by Syn-McJ** [comment]
Hi @mking1011 

It seems like the model works, but it has troubles recognizing raccoons reliably. I can get a glimpse of something that looks like a valid box around a racoon on a picture, but it's inconsistent. The problem can be anywhere from TensorFlowSharp implementation to the model itself, I'm afraid I won't be much of help to you here since my knowledge of TensorFlow is limited. As I mentioned in the readme, performance of the detection example is pretty bad and I'm not sure how to improve that at this moment.

**Comment by mking1011** [comment]
Hi @Syn-McJ 

I am so grateful to have gained a lot of knowledge from you.

I want to ask you one more question.
Why is the yolo model not working?
If the yolo model works, I can solve a lot of things.

**Comment by Syn-McJ** [comment]
Hi @mking1011 

It's a good question. Assuming that YOLO model doesn't use any operations that aren't available on mobile (like `DecodeJpeg`), it should be possible to make it work. I imaging outputs of YOLO model will be totally different from ones in ssd-mobilenet, and possibly input image might need to be decoded differently. TensorFlowSharp repository only have [detection example with ssd-mobilenet model](https://github.com/migueldeicaza/TensorFlowSharp/tree/master/Examples/ExampleObjectDetection), so all I did is just quickly ported it here.

But original Android example have code for both SSD-Mobilenet and YOLO models, and if you can figure out how to translate Java code working with inputs/outputs to C# calling similar TensorFlow APIs, then it might work. [Here is the YOLO detector class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java) from Android example, and [here is the SSD-Mobilenet class](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowObjectDetectionAPIModel.java) that corresponds to what we have in this repository now.

I might try to tackle this problem in future to make YOLO models work, but certainly not any time soon. I also don't think performance will improve significantly with different model architecture. So if you wan't to try and port it, go ahead.

**Comment by mking1011** [comment]
Thank you so much. @Syn-McJ 

I first made .pb files by myself.  It's all your help.
That pb file will distinguish your hand shape.
The .pb file was created via ssd_mobilenet_v1_pets

But when applied to a Unity project, the screen turns white.
Could you tell me why?

**Comment by mking1011** [comment]
Thank you so much. @Syn-McJ

I first made .pb files by myself. It's all your help.
That pb file will distinguish your hand shape.
The .pb file was created via ssd_mobilenet_v1_pets

But when applied to a Unity project, the screen turns white.
Could you tell me why?
[frozen_inference_graph.zip](https://github.com/Syn-McJ/TFClassify-Unity/files/2335551/frozen_inference_graph.zip)

**Comment by Syn-McJ** [comment]
@mking1011 I can't check right now, but if your run `adb logcat -s Unity` to get logs, you might see what the error is

**Comment by reido2012** [comment]
@mking1011 I don't think you can just change the extension from .pb to .bytes anymore. Have a look at this https://blog.goodaudience.com/tensorflow-unity-how-to-set-up-a-custom-tensorflow-graph-in-unity-d65cc1bd1ab1. 

Also if you're using the pretrained ssd_mobilenet_v1_pets model from the google repository, you should be aware that it was trained using TF 1.8 which you can't use with the current TFSharp plugin. So be careful when training your own network make sure it was trained with either TF 1.4 (TF Sharp Plugin 0.3) or TF 1.7 (0.4).

I'm having a problem @Syn-McJ  when I build the Unity application for iOS. The model runs and classifies it's just that when the boxes are being drawn, the boxes are very small in the same general area. The boxes don't bound the objects.

**Comment by Syn-McJ** [comment]
Hi guys, sorry for late response.

@mking1011, I checked logcat and I see this error: `Op type not registered 'NonMaxSuppressionV3' in binary running on localhost.`

It basically means that your model uses an operation that isn't available in TensorFlow binary that is used by Unity plugin. You might find help with this issue [here](https://github.com/tensorflow/tensorflow/issues/19854) or [here](https://github.com/tensorflow/models/issues/4691). Judging by the last link, the problem is indeed might be in mismatch between TF versions like @reido2012 described.

Changing extension should still work fine, the sample obviously reads the model successfully it's just that model is incompatible.

@reido2012 unfortunately, I don't have access to mac right now so I can't check this problem, but seems like it's related to dpi and can probably be solved by tinkering with Unity textures. If you can create a separate issue for this that'd be great, and I'll take a look when I can.

**Comment by mking1011** [comment]
@Syn-McJ, @reido2012 
Thank you both.

But I still have not solved it.
https://towardsdatascience.com/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9

I followed the guide of the link above.
And as you say, I worked on Tensorflow 1.4 and TF Sharp Plugin 0.3.
However, I could see the following error.
Error : TFException. Make sure you model trained with same version of TensorFlow as in Unity plugin..
I do not feel what I did wrong.

I would appreciate a look at my .pb file.

[pb.zip](https://github.com/Syn-McJ/TFClassify-Unity/files/2370500/pb.zip)

**Comment by mking1011** [comment]
@Syn-McJ , @reido2012 
Thank you both.

I have studied in the Tensorflow object dection.
https://github.com/tensorflow/models/tree/master/research/object_detection/

But as he says, if I train the ssd_mobilenet_v1_pets model using the google repository I have to use TF 1.8
Can you teach me how to train the ssd_mobilenet_v1_pets model using TF1.4?

I saw this article. #13

**Comment by mking1011** [comment]
Hi  @Syn-McJ , @reido2012  
I finally found a way to work with TF 1.7 and I did what I wanted.

It would not have been possible without you. I thank you so much.

I wish all of you are doing well.

**Comment by Syn-McJ** [comment]
That's great to hear @mking1011. I'll close this issue now.

**Comment by Amanpradhan** [comment]
> @mking1011 I don't think adding racoon label to coco_labels_list.txt will work, object detection is depending on correct amount of labels and the format of the labels file, which is different for ssd-mobilenet.
> 
> your object-detection.pbtxt file seems to be in the right format, if you rename its extension to .txt and use it as labels file it should work for your model.
> 
> I'll try to find time to check it later today.



> Hi @Syn-McJ , @reido2012
> I finally found a way to work with TF 1.7 and I did what I wanted.
> 
> It would not have been possible without you. I thank you so much.
> 
> I wish all of you are doing well.

Hi @mking1011 , can you please elaborate how you managed to use tensorflow 1.7 for object detection?

**Comment by mking1011** [comment]
Hi @Amanpradhan 

Could you refer to the site below?

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

**Comment by Amanpradhan** [comment]
Hi @mking1011 , I tried training my model from the above link using tensorflow 1.7.1, but when I try to freeze my graph using export_inference_graph.py, I am getting the error - 
TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'
When I look further into the issue, I get to understand that this issue occurs tin tensorflow version < 1.9.0. However, I cannot train my model in 1.9.0 since tensrflow sharp does not support it. How do I train it on 1.7.1?
